#nullable enable // autogenerated

using MVZ2.Vanilla.Properties;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Level;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.SeedPacks
{
    [AutoBuffDefinition(VanillaBuffNames.SeedPack.zeroKSpaceCost)]
    public class ZeroKSpaceCostBuff : BuffDefinition
    {
        public ZeroKSpaceCostBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new FloatModifier(EngineSeedProps.COST, NumberOperator.Multiply, PROP_MULTIPLIER));
        }
        public static readonly VanillaBuffPropertyMeta<float> PROP_MULTIPLIER = new VanillaBuffPropertyMeta<float>("Multiplier", 1);
    }
}
