#nullable enable // autogenerated

using System.Collections.Generic;
using System.Linq;
using MVZ2.GameContent.Buffs.Level;
using MVZ2.GameContent.Enemies;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Blueprints;
using MVZ2Logic.Callbacks;
using MVZ2Logic.Level;
using MVZ2Logic.Spawns;
using PVZEngine;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Grids;
using PVZEngine.Level;
using PVZEngine.Spawns;
using Tools;

namespace MVZ2.GameContent.Stages
{
    public class UnknowPalaceStageBehaviour : StageBehaviour
    {
        public UnknowPalaceStageBehaviour(StageDefinition stageDef) : base(stageDef)
        {
            stageDef.AddTrigger(LogicLevelCallbacks.POST_BLUEPRINT_SELECTION, PostBlueprintSelectionCallback);
            stageDef.AddTrigger(LogicLevelCallbacks.PRE_WAVE_ENEMY_SPAWN, PreWaveEnemySpawnCallback, PRE_WAVE_ENEMY_SPAWN_PRIORITY);
            stageDef.AddTrigger(LogicLevelCallbacks.POST_WAVE_ENEMY_SPAWN, PostWaveEnemySpawnCallback);
        }
        public override void Start(LevelEngine level)
        {
            base.Start(level);
            rng = null;
            EnsurePlanSeed(level);
        }
        public override void PostWave(LevelEngine level, int wave)
        {
            base.PostWave(level, wave);
            // 波次从 1 开始，波 0 为准备阶段。
            if (wave <= 0)
                return;
            var slotCount = level.GetSeedSlotCount();
            if (slotCount <= 0)
                return;
            var recorded = GetRecordedBlueprints(level);
            if (recorded == null || recorded.Length < slotCount)
                return;
            var commandBlocks = GetRecordedCommandBlocks(level);
            if (commandBlocks == null || commandBlocks.Length < slotCount)
                return;
            NamespaceID? target;
            bool targetCommandBlock;
            if (wave <= slotCount)
            {
                // 前 k 波：使用记录中的第 wave 张卡（含未选择的空位）。
                target = recorded[wave - 1];
                targetCommandBlock = commandBlocks[wave - 1];
            }
            else
            {
                // 第 k+1 波起：使用记录中的随机卡。
                if (!TryGetRandomRecorded(level, recorded, commandBlocks, out target, out targetCommandBlock))
                    return;
            }
            ReplaceAllBlueprints(level, target, targetCommandBlock);
        }
        private void PostBlueprintSelectionCallback(LogicLevelCallbacks.PostBlueprintSelectionParams param, CallbackResult result)
        {
            var level = param.level;
            if (!LevelHasBehaviour<UnknowPalaceStageBehaviour>(level))
                return;
            var slotCount = level.GetSeedSlotCount();
            if (slotCount <= 0)
                return;
            // 记录选卡，未选择的槽位留空。
            var recorded = new NamespaceID[slotCount];
            var commandBlocks = new bool[slotCount];
            for (int i = 0; i < param.chosenBlueprints.Length && i < slotCount; i++)
            {
                var item = param.chosenBlueprints[i];
                recorded[i] = item.id;
                commandBlocks[i] = item.isCommandBlock;
            }
            SetRecordedBlueprints(level, recorded);
            SetRecordedCommandBlocks(level, commandBlocks);
        }
        #region 自定义出怪规则
        private void PreWaveEnemySpawnCallback(LogicLevelCallbacks.WaveEnemySpawnParams args, CallbackResult result)
        {
            var level = args.level;
            if (!LevelHasBehaviour<UnknowPalaceStageBehaviour>(level))
                return;
            // 将原版生成点数置 0，抑制原版出怪循环（本关出怪由 PostWaveEnemySpawnCallback 接管）。
            result.SetValue(0);
            // 最后一波：抑制原版“未生成过的怪物强制生成一次”的规则。
            if (level.IsFinalWave(args.wave))
            {
                var pool = level.GetEnemyPool();
                if (pool == null)
                    return;
                foreach (var id in pool)
                {
                    level.AddSpawnedEnemyID(id);
                }
            }
        }
        private void PostWaveEnemySpawnCallback(LogicLevelCallbacks.WaveEnemySpawnParams args, CallbackResult result)
        {
            var level = args.level;
            if (!LevelHasBehaviour<UnknowPalaceStageBehaviour>(level))
                return;
            var wave = args.wave;
            if (wave <= 0)
                return;
            EnsurePlanSeed(level);

            // 最后一波：每一路生成列表中所有怪种各一只，无视生成数量限制。
            if (level.IsFinalWave(wave))
            {
                RemoveVanillaUFOBuffs(level);
                SpawnFinalWaveScript(level);
                result.SetValue(0);
                return;
            }

            var types = GetWaveTypes(level, wave);
            if (types.Length <= 0)
                return;
            // 移除原版 UFO 日程增益，避免每 5 波一次的固定生成（原版按原始点数计算数量，无法被点数置 0 抑制）。
            RemoveVanillaUFOBuffs(level);
            var totalPoints = args.maxPoints;
            int spawnedCount = 0;
            var rng = level.GetSpawnRNG();
            while (totalPoints > 0 && spawnedCount < MAX_SPAWN_COUNT)
            {
                var type = types[rng.Next(types.Length)];
                var spawnDef = level.Content.GetSpawnDefinition(type);
                if (spawnDef == null)
                    break;
                if (type == VanillaSpawnID.GetFromEntity(VanillaEnemyID.ufo))
                {
                    // UFO 立即生成。
                    SpawnUFOImmediate(level);
                }
                else
                {
                    level.SpawnEnemyAtRandomLane(spawnDef);
                }
                totalPoints -= spawnDef.GetSpawnLevel();
                spawnedCount++;
            }
            result.SetValue(totalPoints);
        }
        private NamespaceID[] GetWaveTypes(LevelEngine level, int wave)
        {
            var pool = level.GetEnemyPool();
            if (pool == null || pool.Length <= 0)
                return System.Array.Empty<NamespaceID>();
            var rng = new RandomGenerator(GetPlanSeed(level));
            if (wave >= 1 && wave <= FIRST_PHASE_WAVE_COUNT)
            {
                // 前九波：每波一种，互不重复，不含 mega_mutant_zombie。
                var nonMega = pool.Where(id => id != VanillaSpawnID.megaMutantZombie).ToArray();
                nonMega.Shuffle(rng);
                if (wave - 1 >= nonMega.Length)
                    return System.Array.Empty<NamespaceID>();
                return new NamespaceID[] { nonMega[wave - 1] };
            }
            if (wave == MEGA_MUTANT_WAVE)
            {
                // 第十波：固定为 mega_mutant_zombie。
                return new NamespaceID[] { VanillaSpawnID.megaMutantZombie };
            }
            if (wave >= SECOND_PHASE_START_WAVE)
            {
                // 第 11 波起：种类逐波 +1（第 11 波 2 种、第 12 波 3 种……），波内不重复，波次间可重复。
                var count = wave - (SECOND_PHASE_START_WAVE - 1);
                var shuffled = pool.ToArray();
                shuffled.Shuffle(rng);
                return shuffled.Take(count).ToArray();
            }
            return System.Array.Empty<NamespaceID>();
        }
        private void RemoveVanillaUFOBuffs(LevelEngine level)
        {
            foreach (var buff in level.GetBuffs<UFOSpawnBuff>())
            {
                buff.Remove();
            }
        }
        private void SpawnUFOImmediate(LevelEngine level)
        {
            var variantPool = new List<int>();
            UndeadFlyingObject.FillUFOVariantRandomPool(level, level.Option.RightFaction, variantPool);
            if (variantPool.Count <= 0)
                return;
            var rng = level.GetSpawnRNG();
            var variant = variantPool[rng.Next(variantPool.Count)];
            var possibleGrids = new HashSet<LawnGrid>();
            UndeadFlyingObject.FillUFOPossibleSpawnGrids(level, variant, level.Option.RightFaction, possibleGrids);
            var filteredGrids = UndeadFlyingObject.FilterConflictSpawnGrids(level, possibleGrids);
            if (filteredGrids.Count() <= 0)
                return;
            var grid = filteredGrids.Random(rng);
            if (grid == null)
                return;
            var enemy = UndeadFlyingObject.SpawnAtGrid(grid, variant);
            if (enemy != null)
            {
                level.TriggerEnemySpawned(VanillaSpawnID.GetFromEntity(VanillaEnemyID.ufo), enemy);
            }
        }
        private void SpawnFinalWaveScript(LevelEngine level)
        {
            var pool = level.GetEnemyPool();
            if (pool == null)
                return;
            var spawnDefs = pool.Select(id => level.Content.GetSpawnDefinition(id)).OfType<SpawnDefinition>().ToArray();
            for (int lane = 0; lane < level.GetMaxLaneCount(); lane++)
            {
                foreach (var spawnDef in spawnDefs)
                {
                    if (spawnDef.GetID() == VanillaSpawnID.GetFromEntity(VanillaEnemyID.ufo))
                    {
                        SpawnUFOAtLane(level, lane);
                    }
                    else
                    {
                        level.SpawnEnemy(spawnDef, lane);
                    }
                }
            }
        }
        private void SpawnUFOAtLane(LevelEngine level, int lane)
        {
            var variantPool = new List<int>();
            UndeadFlyingObject.FillUFOVariantRandomPool(level, level.Option.RightFaction, variantPool);
            if (variantPool.Count <= 0)
                return;
            var variant = variantPool[level.GetSpawnRNG().Next(variantPool.Count)];
            var grid = GetSpawnGridAtLane(level, lane);
            if (grid == null)
                return;
            var enemy = UndeadFlyingObject.SpawnAtGrid(grid, variant);
            if (enemy != null)
            {
                level.TriggerEnemySpawned(VanillaSpawnID.GetFromEntity(VanillaEnemyID.ufo), enemy);
            }
        }
        private LawnGrid? GetSpawnGridAtLane(LevelEngine level, int lane)
        {
            for (int column = level.GetMaxColumnCount() - 1; column >= 0; column--)
            {
                var grid = level.GetGrid(column, lane);
                if (grid != null)
                    return grid;
            }
            return null;
        }
        private void EnsurePlanSeed(LevelEngine level)
        {
            if (level.TryGetProperty<int>(PROP_PLAN_SEED, out _))
                return;
            var seed = level.GetSpawnRNG().Next();
            if (seed == 0)
                seed = 1;
            SetPlanSeed(level, seed);
        }
        #endregion
        private bool TryGetRandomRecorded(LevelEngine level, NamespaceID[] recorded, bool[] commandBlocks, out NamespaceID? target, out bool targetCommandBlock)
        {
            var validIndices = new List<int>();
            for (int i = 0; i < recorded.Length; i++)
            {
                if (recorded[i] != null)
                    validIndices.Add(i);
            }
            if (validIndices.Count <= 0)
            {
                target = null;
                targetCommandBlock = false;
                return false;
            }
            rng ??= level.CreateRNG();
            var index = validIndices[rng.Next(validIndices.Count)];
            target = recorded[index];
            targetCommandBlock = commandBlocks[index];
            return true;
        }
        private void ReplaceAllBlueprints(LevelEngine level, NamespaceID? target, bool commandBlock)
        {
            for (int i = 0; i < level.GetSeedSlotCount(); i++)
            {
                if (target == null)
                {
                    // 记录的该槽位为空，清空卡槽。
                    level.RemoveSeedPackAt(i);
                    continue;
                }
                var seed = level.CreateSeedPack(target);
                if (seed == null)
                    continue;
                seed.SetCommandBlock(commandBlock);
                // 替换后立即充满充能，无需等待初始充能时间。
                seed.SetStartRecharge(true);
                seed.FullRecharge();
                level.ReplaceSeedPackAt(i, seed);
            }
        }
        public static NamespaceID[]? GetRecordedBlueprints(LevelEngine level) => level.GetProperty<NamespaceID[]>(PROP_RECORDED_BLUEPRINTS);
        public static void SetRecordedBlueprints(LevelEngine level, NamespaceID[] value) => level.SetProperty(PROP_RECORDED_BLUEPRINTS, value);
        public static bool[]? GetRecordedCommandBlocks(LevelEngine level) => level.GetProperty<bool[]>(PROP_RECORDED_COMMAND_BLOCKS);
        public static void SetRecordedCommandBlocks(LevelEngine level, bool[] value) => level.SetProperty(PROP_RECORDED_COMMAND_BLOCKS, value);
        public static int GetPlanSeed(LevelEngine level) => level.GetProperty<int>(PROP_PLAN_SEED);
        public static void SetPlanSeed(LevelEngine level, int value) => level.SetProperty(PROP_PLAN_SEED, value);
        private const string PROP_REGION = "unknow_palace_stage";
        [LevelPropertyRegistry(PROP_REGION)]
        public static readonly VanillaLevelPropertyMeta<NamespaceID[]> PROP_RECORDED_BLUEPRINTS = new VanillaLevelPropertyMeta<NamespaceID[]>("recordedBlueprints");
        [LevelPropertyRegistry(PROP_REGION)]
        public static readonly VanillaLevelPropertyMeta<bool[]> PROP_RECORDED_COMMAND_BLOCKS = new VanillaLevelPropertyMeta<bool[]>("recordedCommandBlocks");
        [LevelPropertyRegistry(PROP_REGION)]
        public static readonly VanillaLevelPropertyMeta<int> PROP_PLAN_SEED = new VanillaLevelPropertyMeta<int>("planSeed");
        /// <summary>
        /// 前九波每波一种怪，互不重复（不含 mega_mutant_zombie）。
        /// </summary>
        public const int FIRST_PHASE_WAVE_COUNT = 9;
        /// <summary>
        /// 第十波固定为 mega_mutant_zombie。
        /// </summary>
        public const int MEGA_MUTANT_WAVE = 10;
        /// <summary>
        /// 第 11 波起每波种类 +1（第 11 波 2 种、第 12 波 3 种……）。
        /// </summary>
        public const int SECOND_PHASE_START_WAVE = 11;
        /// <summary>
        /// 原版的单波生成数量上限（最后一波无视该限制）。
        /// </summary>
        public const int MAX_SPAWN_COUNT = 50;
        /// <summary>
        /// 高优先级最后执行，确保原版出怪点数最终被置 0（UFO 生成增益仍会照常生成）。
        /// </summary>
        public const int PRE_WAVE_ENEMY_SPAWN_PRIORITY = 1000;
        private RandomGenerator? rng;
    }
}
