#nullable enable // autogenerated

using MVZ2.GameContent.Buffs.SeedPacks;
using MVZ2.GameContent.Pickups;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Entities;
using PVZEngine.Level;
using PVZEngine.Modifiers;
using PVZEngine.SeedPacks;
using UnityEngine;

namespace MVZ2.GameContent.Stages
{
    public class ZeroKSpaceStageBehaviour : StageBehaviour
    {
        public ZeroKSpaceStageBehaviour(StageDefinition stageDef) : base(stageDef)
        {
            AddModifier(new FloatModifier(EngineLevelProps.RECHARGE_SPEED, NumberOperator.Set, INSTANT_RECHARGE_SPEED));
            stageDef.AddTrigger(LevelCallbacks.POST_ENTITY_INIT, PostEntityInitCallback, filter: EntityTypes.PICKUP);
        }
        public override void Update(LevelEngine level)
        {
            base.Update(level);
            for (int i = 0; i < level.GetSeedSlotCount(); i++)
            {
                var seedPack = level.GetSeedPackAt(i);
                if (seedPack == null || seedPack.HasBuff<ZeroKSpaceCostBuff>())
                    continue;
                var buff = seedPack.NewBuff<ZeroKSpaceCostBuff>();
                buff.SetProperty(ZeroKSpaceCostBuff.PROP_MULTIPLIER, GetCostMultiplier(seedPack));
                seedPack.AddBuff(buff);
            }
        }
        private void PostEntityInitCallback(EntityCallbackParams param, CallbackResult result)
        {
            var entity = param.entity;
            var definitionID = entity.GetDefinitionID();
            if (definitionID != VanillaPickupID.gunpowder && definitionID != VanillaPickupID.furiousGunpowder)
                return;
            entity.Timeout = GUNPOWDER_EXPLODE_TIMEOUT;
        }
        private static float GetCostMultiplier(SeedPack seedPack)
        {
            var rechargeDef = seedPack.GetRechargeDefinition();
            if (rechargeDef == null)
                return 1;
            return Mathf.Max(1, rechargeDef.GetQuality());
        }
        /// <summary>
        /// 足够大的充能速度，使所有蓝图充能时间固定为 0（瞬间充能完成）。
        /// </summary>
        public const float INSTANT_RECHARGE_SPEED = 99999999;
        /// <summary>
        /// 火药爆炸前的帧数。
        /// </summary>
        public const int GUNPOWDER_EXPLODE_TIMEOUT = 3;
    }
}
